repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-toml

  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pdm-project/pdm
    rev: 2.23.0
    hooks:
      - id: pdm-lock-check
      - id: pdm-export
        args: ['-o', 'requirements.txt', '--without-hashes']
        files: ^pdm.lock$


ci:
  autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit.com hooks"
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  submodules: false
